# Conda environment for SPC
name: SPC
channels:
 - conda-forge
dependencies:
 # Environment management tools
 - python=3.8
 - pip=22.0.3
 # Jupyter & interactive stuff
 - jupyterlab=3.2.9
 # Scientific Python
 - numpy=1.22.2 
 # Data tools
 - pandas=1.4.1
 - xarray=0.21.1
 # Visualisation
 - matplotlib=3.5.1
 - seaborn=0.11
 - plotly==5.7.0
 # Progress Bars and user interaction
 - tqdm=4.62.3
 - click=8.0.3
 - PyYAML=6.0
 # Geospatial
 - geopandas=0.10.2
 - cartopy=0.20.2
 - pip:
    - py-markdown-table
    - protobuf
