// @generated by protoc-gen-es v1.0.0 with parameter "target=js"
// @generated from file synthpop.proto (package synthpop, syntax proto2)
/* eslint-disable */
// @ts-nocheck

import { proto2 } from "@bufbuild/protobuf";

/**
 * @generated from enum synthpop.Sex
 */
export const Sex = proto2.makeEnum(
  "synthpop.Sex",
  [
    {no: 1, name: "MALE"},
    {no: 2, name: "FEMALE"},
  ],
);

/**
 * @generated from enum synthpop.Origin
 */
export const Origin = proto2.makeEnum(
  "synthpop.Origin",
  [
    {no: 1, name: "WHITE"},
    {no: 2, name: "BLACK"},
    {no: 3, name: "ASIAN"},
    {no: 4, name: "MIXED"},
    {no: 5, name: "OTHER"},
  ],
);

/**
 * National Statistics socio-economic classification
 *
 * @generated from enum synthpop.NSSEC5
 */
export const NSSEC5 = proto2.makeEnum(
  "synthpop.NSSEC5",
  [
    {no: 0, name: "UNEMPLOYED"},
    {no: 1, name: "HIGHER"},
    {no: 2, name: "INTERMEDIATE"},
    {no: 3, name: "SMALL"},
    {no: 4, name: "LOWER"},
    {no: 5, name: "ROUTINE"},
  ],
);

/**
 * Professional working status, from the time-use survey
 *
 * @generated from enum synthpop.PwkStat
 */
export const PwkStat = proto2.makeEnum(
  "synthpop.PwkStat",
  [
    {no: 0, name: "NA"},
    {no: 1, name: "EMPLOYEE_FT"},
    {no: 2, name: "EMPLOYEE_PT"},
    {no: 3, name: "EMPLOYEE_UNSPEC"},
    {no: 4, name: "SELF_EMPLOYED"},
    {no: 5, name: "PWK_UNEMPLOYED"},
    {no: 6, name: "RETIRED"},
    {no: 7, name: "HOMEMAKER"},
    {no: 8, name: "STUDENT_FT"},
    {no: 9, name: "LONG_TERM_SICK"},
    {no: 10, name: "PWK_OTHER"},
  ],
);

/**
 * Body Mass Index
 *
 * @generated from enum synthpop.BMI
 */
export const BMI = proto2.makeEnum(
  "synthpop.BMI",
  [
    {no: 0, name: "NOT_APPLICABLE"},
    {no: 1, name: "UNDERWEIGHT"},
    {no: 2, name: "NORMAL"},
    {no: 3, name: "OVERWEIGHT"},
    {no: 4, name: "OBESE_1"},
    {no: 5, name: "OBESE_2"},
    {no: 6, name: "OBESE_3"},
  ],
);

/**
 * @generated from enum synthpop.Activity
 */
export const Activity = proto2.makeEnum(
  "synthpop.Activity",
  [
    {no: 0, name: "RETAIL"},
    {no: 1, name: "PRIMARY_SCHOOL"},
    {no: 2, name: "SECONDARY_SCHOOL"},
    {no: 3, name: "HOME"},
    {no: 4, name: "WORK"},
  ],
);

/**
 * @generated from message synthpop.Population
 */
export const Population = proto2.makeMessageType(
  "synthpop.Population",
  () => [
    { no: 1, name: "households", kind: "message", T: Household, repeated: true },
    { no: 2, name: "people", kind: "message", T: Person, repeated: true },
    { no: 3, name: "venues_per_activity", kind: "map", K: 5 /* ScalarType.INT32 */, V: {kind: "message", T: VenueList} },
    { no: 4, name: "info_per_msoa", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: InfoPerMSOA} },
    { no: 5, name: "lockdown", kind: "message", T: Lockdown },
  ],
);

/**
 * @generated from message synthpop.Household
 */
export const Household = proto2.makeMessageType(
  "synthpop.Household",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "msoa11cd", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "orig_hid", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "members", kind: "scalar", T: 4 /* ScalarType.UINT64 */, repeated: true },
  ],
);

/**
 * @generated from message synthpop.VenueList
 */
export const VenueList = proto2.makeMessageType(
  "synthpop.VenueList",
  () => [
    { no: 1, name: "venues", kind: "message", T: Venue, repeated: true },
  ],
);

/**
 * @generated from message synthpop.InfoPerMSOA
 */
export const InfoPerMSOA = proto2.makeMessageType(
  "synthpop.InfoPerMSOA",
  () => [
    { no: 1, name: "shape", kind: "message", T: Point, repeated: true },
    { no: 2, name: "population", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "buildings", kind: "message", T: Point, repeated: true },
    { no: 4, name: "flows_per_activity", kind: "message", T: Flows, repeated: true },
  ],
);

/**
 * In WGS84
 *
 * @generated from message synthpop.Point
 */
export const Point = proto2.makeMessageType(
  "synthpop.Point",
  () => [
    { no: 1, name: "longitude", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 2, name: "latitude", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
  ],
);

/**
 * @generated from message synthpop.Person
 */
export const Person = proto2.makeMessageType(
  "synthpop.Person",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "household", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "workplace", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 4, name: "identifiers", kind: "message", T: Identifiers },
    { no: 5, name: "demographics", kind: "message", T: Demographics },
    { no: 6, name: "employment", kind: "message", T: Employment },
    { no: 7, name: "health", kind: "message", T: Health },
    { no: 8, name: "time_use", kind: "message", T: TimeUse },
    { no: 9, name: "activity_durations", kind: "message", T: ActivityDuration, repeated: true },
  ],
);

/**
 * What fraction of a day somebody spends doing an activity.
 *
 * @generated from message synthpop.ActivityDuration
 */
export const ActivityDuration = proto2.makeMessageType(
  "synthpop.ActivityDuration",
  () => [
    { no: 1, name: "activity", kind: "enum", T: proto2.getEnumType(Activity) },
    { no: 2, name: "duration", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * @generated from message synthpop.Identifiers
 */
export const Identifiers = proto2.makeMessageType(
  "synthpop.Identifiers",
  () => [
    { no: 1, name: "pid_census", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "pid_tus", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "pid_hse", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "idp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message synthpop.Demographics
 */
export const Demographics = proto2.makeMessageType(
  "synthpop.Demographics",
  () => [
    { no: 1, name: "sex", kind: "enum", T: proto2.getEnumType(Sex) },
    { no: 2, name: "age_years", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "origin", kind: "enum", T: proto2.getEnumType(Origin) },
    { no: 4, name: "socioeconomic_classification", kind: "enum", T: proto2.getEnumType(NSSEC5) },
  ],
);

/**
 * @generated from message synthpop.Employment
 */
export const Employment = proto2.makeMessageType(
  "synthpop.Employment",
  () => [
    { no: 1, name: "sic1d07", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 2, name: "sic2d07", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 3, name: "soc2010", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 4, name: "pwkstat", kind: "enum", T: proto2.getEnumType(PwkStat) },
    { no: 5, name: "salary_yearly", kind: "scalar", T: 2 /* ScalarType.FLOAT */, opt: true },
    { no: 6, name: "salary_hourly", kind: "scalar", T: 2 /* ScalarType.FLOAT */, opt: true },
  ],
);

/**
 * @generated from message synthpop.Health
 */
export const Health = proto2.makeMessageType(
  "synthpop.Health",
  () => [
    { no: 1, name: "bmi", kind: "enum", T: proto2.getEnumType(BMI) },
    { no: 5, name: "bmi_new", kind: "scalar", T: 2 /* ScalarType.FLOAT */, opt: true },
    { no: 2, name: "has_cardiovascular_disease", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "has_diabetes", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "has_high_blood_pressure", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * The proportion of a day spent doing different daily activities.
 * unknown + work + school + shop + services + leisure + escort + transport = not_home
 * home + work_home = home_total
 * not_home + home_total = 1
 *
 * @generated from message synthpop.TimeUse
 */
export const TimeUse = proto2.makeMessageType(
  "synthpop.TimeUse",
  () => [
    { no: 1, name: "unknown", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "work", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "school", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "shop", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "services", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 6, name: "leisure", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 7, name: "escort", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 8, name: "transport", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 9, name: "not_home", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 10, name: "home", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 11, name: "work_home", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 12, name: "home_total", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * Per activity, a list of venues where anybody living in a certain MSOA is
 * likely to go do that activity.
 *
 * @generated from message synthpop.Flows
 */
export const Flows = proto2.makeMessageType(
  "synthpop.Flows",
  () => [
    { no: 1, name: "activity", kind: "enum", T: proto2.getEnumType(Activity) },
    { no: 2, name: "flows", kind: "message", T: Flow, repeated: true },
  ],
);

/**
 * @generated from message synthpop.Flow
 */
export const Flow = proto2.makeMessageType(
  "synthpop.Flow",
  () => [
    { no: 1, name: "venue_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "weight", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * Represents a place where people do an activity
 *
 * @generated from message synthpop.Venue
 */
export const Venue = proto2.makeMessageType(
  "synthpop.Venue",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "activity", kind: "enum", T: proto2.getEnumType(Activity) },
    { no: 3, name: "location", kind: "message", T: Point },
    { no: 4, name: "urn", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * Describes a reduction in daily travel behavior due to COVID lockdowns.
 *
 * @generated from message synthpop.Lockdown
 */
export const Lockdown = proto2.makeMessageType(
  "synthpop.Lockdown",
  () => [
    { no: 1, name: "start_date", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "per_day", kind: "scalar", T: 2 /* ScalarType.FLOAT */, repeated: true },
  ],
);

