project:
  type: book

book:
  title: "Synthetic Population Catalyst"
  search: true
  repo-url: https://github.com/alan-turing-institute/uatk-spc/tree/main/docs
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: "Using SPC"
      chapters:
        - outputs.qmd
        - england_outputs.qmd
        - wales_outputs.qmd
        - use_output.qmd
        - installation.qmd
        - custom_areas.qmd
    - part: "Understanding SPC"
      chapters:
        - schema.qmd
        - modelling_methods.qmd
        - data_sources.qmd
    - part: "Advanced"
      chapters:
        - developer_guide.qmd
        - code_walkthrough.qmd
        - performance.qmd

format:
  html:
    theme: cosmo
  pdf: default
