project:
  type: book

book:
  title: "Synthetic Population Catalyst"
  search: true
  repo-url: https://github.com/alan-turing-institute/uatk-spc/tree/main/docs
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: "Using SPC"
      chapters:
        - using_getting_started.qmd
        - using_outputs.qmd
        - using_england_outputs.qmd
        - using_wales_outputs.qmd
        - using_scotland_outputs.qmd
        - using_use_output.qmd
        - using_installation.qmd
        - using_custom_areas.qmd
    - part: "Understanding SPC"
      chapters:
        - understanding_introduction.qmd
        - understanding_technical_overview.qmd
        - understanding_modelling_methods.qmd
        - understanding_data_schema.qmd
        - understanding_data_sources.qmd
    - validation.qmd
    - part: "Advanced"
      chapters:
        - advanced_developer_guide.qmd
        - advanced_code_walkthrough.qmd
        - advanced_performance.qmd

format:
  html:
    theme: cosmo
  pdf: default
