---
title: "Data sources"
toc: true
---

The original data are provided at different scales, which define their level of accuracy. For simplicity, the outputs of SPC are geolocated at Output Area (OA) level, although this scale may not be relevant to all indicators. The 2011 OAs are a geographical unit created for census collection and are designed to be relatively homogeneous, with an average size between 120 and 129 households.

The data from Open Street Map (OSM) is downloaded directly from https://www.openstreetmap.org. Everything else is hosted through local copies inside one Azure repository that interacts automatically with the model. We describe below the content of this repository and indicate the raw source used for each indicator. It is divided into utilities, county level data and national data. To recreate the content of this repository from raw sources, please refer to [this part of the code](https://github.com/alan-turing-institute/uatk-spc/tree/main/scripts/data_prep).

## Utility data

# [lookUp-GB.csv.gz](https://ramp0storage.blob.core.windows.net/referencedata/lookUp-GB.csv.gz)

The look-up table links different geographies of Great Britain together. It is used internally by the model, but can also help the user define their own study area. The following are standard denominations, compatible with ONS fields of the same name. They are based on ONS [lookups](https://geoportal.statistics.gov.uk/). See ONS documentation for more details.

- `OA11CD`: Output area codes for the 2011 census (120 to 129 households)
- `LSOA11CD` & `LSOA11NM`: Lower-layer Super Output Areas (about 2000 individuals), replaced by Intermediary Zones for Scotland
- `MSOA11CD`,`MSOA11NM`: Middle-layer Super Output Areas (about 8000 individuals), replaced by Data Zones for Scotland
- `LAD20CD`, `LAD20NM`: Local Authority Districts (314 for England, 22 for Wales and 32 for Scotland)
- `ITL321CD`, `ITL321NM`, `ITL221CD`, `ITL221NM`, `ITL121CD` & `ITL121NM`: International Territorial Level, replacing pre-Brexit NUTS European divisions.
- `RGN20CD` & `RGN20NM`: Regions of England (NA for other Wales and Scotland)
- `Country`: England, Wales or Scotland

In addition,

- "AzureRef": Name of the geographical unit for the County level data folder inside Azure (Lieutenancy Areas -- a.k.a. Ceremonial Counties -- for England, Scottish Police Divisions and ITL321NM for Wales)
For Wales: ITL321NM
- "GoogleMob" & "OSM" are alternate spellings used by Google and OSM for their data releases.

## County level data

Files in this section are grouped by country (England, Wales and Scotland), then date (2012, 2020, 2022, 2032, 2039). The format of a path to an individual file is:
```
https://ramp0storage.blob.core.windows.net/countydata-v2/[country]/[date]/pop_[area_name].csv.gz
```
As of March 2023, England contains 5 series of 46 files (Dorset is missing), Wales 5 series of 12 files and Scotland is missing.

# pop_<area_name>.csv.gz

The data is mainly based on the [2011 UK census](http://dx.doi.org/10.5257/census/aggregate-2011-1), the UK [Time Use Survey 2014-15](http://dx.doi.org/10.5255/UKDA-SN-8128-1) and the health surveys of GB ([England](http://dx.doi.org/10.5255/UKDA-SN-8488-2), [Wales](http://dx.doi.org/10.5255/UKDA-SN-8090-1), [Scotland](http://dx.doi.org/10.5255/UKDA-SN-8737-1)). The SPENSER (Synthetic Population Estimation and Scenario Projection) microsimulation model ([ref](http://dx.doi.org/10.1111/gean.12320)) distributes individuals from the census with MSOA scale constraints into synthetic households with OA constraints. It is able to project this synthetic population in the future according to estimates from the Office for National Statistics (ONS). These data were enriched with some of the content of the other datasets mentioned (the rest of which can be added _a posteriori_ from the identifiers provided). The data have also been complented with a modelling of BMI and salaries. The methods used to join the different datasets are explained in the [methods](https://alan-turing-institute.github.io/uatk-spc/modelling_methods.html).

The fields currently contained are:

- `idp`: a unique global individual identifier across all counties
- `MSOA11CD`: MSOA code where the individual lives
- `hid`: household identifier, includes communal establishments
- `pid`: identifier linking to the 2011 Census
- `pid_tus`: identifier linking to the Time Use Survey 2015
- `pid_hse`: identifier linking to the Health Survey for England 2017
- `sex`: 0 female; 1 male
- `age`: in years
- `origin`: 1 White; 2 Black; 3 Asian; 4 Mixed; 5 Other
- `nssec5`: National Statistics Socio-economic classification:
  - 1: Higher managerial, administrative and professional occupations
  - 2: Intermediate occupations
  - 3: Small employers and own account workers
  - 4: Lower supervisory and technical occupations
  - 5: Semi-routine and routine occupations
  - 0: Never worked and long-term unemployed
- `soc2010`: Previous version of the [Standard Occupational Classification](https://www.ons.gov.uk/methodology/classificationsandstandards/standardoccupationalclassificationsoc/soc2010)
- `sic1d07`: Standard [Industrial Classification of Economic Activities 2007](https://www.ons.gov.uk/methodology/classificationsandstandards/ukstandardindustrialclassificationofeconomicactivities), 1st layer (number corresponding to the letter in alphabetical order)
- `sic2d07`: Standard [Industrial Classification of Economic Activities 2007](https://www.ons.gov.uk/methodology/classificationsandstandards/ukstandardindustrialclassificationofeconomicactivities), 2nd layer
- `pwkstat`: Employment status according to the TUS
- Proportion of 24h spent doing different daily activities:
  - `punknown` + `pwork` + `pschool` + `pshop` + `pservices` + `pleisure` + `pescort` + `ptransport` = `pnothome`
  - `phome` + `pworkhome` = `phometot`
  - `pnothome` + `phometot` = 1
- `IncomeX`: hourly (X = "H") and annual (X = "Y") income for employees, see [modelling methods](https://alan-turing-institute.github.io/uatk-spc/modelling_methods.html) for more details
- `cvd`: has a cardio-vascular disease (0 or 1)
- `diabetes`: has diabetes (0 or 1)
- `bloodpressure`: has high blood pressure (0 or 1)
- `BMIvg6`: Body Mass Index:
  - Not applicable
  - Underweight: less than 18.5
  - Normal: 18.5 to less than 25
  - Overweight: 25 to less than 30
  - Obese I: 30 to less than 35
  - Obese II: 35 to less than 40
  - Obese III: 40 or more
- `bmiNew` is a float estimated value for the BMI of the individual. These were drawn directly according to age, sex and ethnicity and are completely independent of the above values (see [modelling methods](https://alan-turing-institute.github.io/uatk-spc/modelling_methods.html)).
- `lng`: longitude of the MSOA11CD centroid
- `lat`: latitude of the MSOA11CD centroid

Some other fields were kept from and for other specific projects but are not from official sources and should generally not be used.

## National data

```
businessRegistry.csv
```

Contains a breakdown of all business units (i.e. a single workplace) in England at LSOA scale (smaller than MSOA), estimated by the project contributors from two nomis datasets: [UK Business Counts - local units by industry and employment size band 2020](https://www.nomisweb.co.uk/datasets/idbrlu) and [Business Register and Employment Survey 2015](https://www.nomisweb.co.uk/datasets/newbrespub). Each item contains the `size` of the unit and its main `sic1d07` code in reference to standard [Industrial Classification of Economic Activities 2007](https://www.ons.gov.uk/methodology/classificationsandstandards/ukstandardindustrialclassificationofeconomicactivities) (number corresponding to the letter in alphabetical order). It is used to compute commuting flows.

The <i>R</i> codes to compute this file are [here](https://github.com/alan-turing-institute/uatk-spc/blob/main/scripts/data_prep/createWorkplaceFile.R).

```
MSOAS_shp.tar.gz
```

Is a simple shapefile taken from ONS [boundaries](https://geoportal.statistics.gov.uk/).

```
QUANT_RAMP.tar.gz
```

See: Milton R, Batty M, Dennett A, dedicated [RAMP Spatial Interaction Model GitHub repository](https://github.com/maptube/QUANT_RAMP). It is used to compute the flows towards schools and retail.

```
timeAtHomeIncreaseCTY.csv
```

This file is a subset from [Google COVID-19 Community Mobility Reports](https://www.google.com/covid19/mobility/), cropped to England. It describes the daily reduction in mobility, averaged at county level, due to lockdown and other COVID-19 restrictions between the 15<sup>th</sup> of February 2020 and 15<sup>th</sup> of April 2022. Missing values have been replaced by the national average. These values can be used directly to reduce `pnothome` and increase `phometot` (and their sub-categories) to simulate more accurately the period.

The <i>R</i> codes to process these data are [here](https://github.com/alan-turing-institute/uatk-spc/blob/main/scripts/data_prep/createMobilityFile.R).
