---
title: "Developer guide"
toc: true
---

## Updating the docs

The site is built with [Quarto](https://quarto.org/). You can iterate on it
locally: `cd docs; quarto preview`

## Code hygiene

We use automated tools to format the code.

```shell
cargo fmt

# Format Markdown docs
prettier --write *.md
prettier --write docs/*.qmd --parser markdown
```

Install [prettier](https://prettier.io) for Markdown.

## Some tips for working with Rust

There are two equivalent ways to rebuild and then run the code. First:

```shell
cargo run --release -- devon
```

The `--` separates arguments to `cargo`, the Rust build tool, and arguments to
the program itself. The second way:

```shell
cargo build --release
./target/release/aspics devon
```

You can build the code in two ways -- **debug** and **release**. There's a
simple tradeoff -- debug mode is fast to build, but slow to run. Release mode is
slow to build, but fast to run. For the ASPICS codebase, since the input data is
so large and the codebase so small, I'd recommend always using `--release`. If
you want to use debug mode, just omit the flag.

If you're working on the Rust code outside of an IDE like
[VSCode](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust),
then you can check if the code compiles much faster by doing `cargo check`.

## Docker

We provide a Dockerfile in case it's helpful for running, but don't recommend
using it. If you want to, then assuming you have Docker setup:

```shell
docker build -t spc .
docker run --mount type=bind,source="$(pwd)"/data,target=/spc/data -t spc /spc/target/release/spc config/bristol.txt
```

This will make the `data` directory in your directory available to the Docker
image, where it'll download the large input files and produce the final output.
