---
title: "Getting started"
toc: true
---
## What SPC does?

The SPC generates spatially enriched synthetic population outputs for multiple administrative and census boundaries including Local Authority Districts - LADs and Counties across England. The output file generated by SPC has a granularity of Middle Layer Super Output Areas - MSOAs. This file is estructured and convided to help other researchers or urban analysts to feed other dynamic models for multiples propouses where a enriched sythetic population file is requiered. SPC includes an comprenhenvise set of variables that include social-demogragfics characterictis, dayliy activities and other extra data sources to help you model the complexity of British society. 

For information about the data sources and the varibles integrated in the SPC outfile, visit [data sources](data_sources.qmd). For information about the administrative and census boundaries included in SPC visit the [Open Geography portal](https://geoportal.statistics.gov.uk/) from the Office for National Statistics (ONS).

## What is the output generated by SPC?

SPC creates Google's [protocol buffer files](https://developers.google.com/protocol-buffers/docs/overview) a platform-neutral, extensible mechanism for serializing structured data in bi-directional way (forward-compatible and backward-compatible). SPC encodes the enriched synthetic population [schema](https://github.com/alan-turing-institute/uatk-spc/blob/main/synthpop.proto) in .proto files (.pb). You can read the "protobuf" (shorthand for a protocol buffer file) in any
[supported language](https://developers.google.com/protocol-buffers/docs/overview#cross-lang),
and then extract and transform just the parts of the data you want.



Note that per MSOA, very few venues are represented as destinations -- 10 for
retail and 5 for school. Only the most likely venues from QUANT are used.

See the [ASPICS conversion
script](https://github.com/alan-turing-institute/uatk-aspics/blob/c8ad47cb01b084028b2f8ca90fcf078470efbee0/convert_snapshot.py#L166)
for all of this in action -- it has a function to collapse a person's flows
down into a single weighted list.

## Areas ready to use and explore

If all you need is to explore the enriched syntetic population file and mesuare if fits to you model, we have created the output file for **all counties in England**, so if the area you want to model is listed or you just want to explore the data, no need to run SPC yourself -- just [download data for your area](outputs.qmd).

If you are interested in create another area or combination of MSOAs, you will need then install and run SPC in your environment. We have tested SPC in Lunix and MacOS systems, for the moment there is no support for Windows systems, but we are working hard to address that.
