---
title: "Installation"
toc: true
---

You only need to compile SPC to run for a custom set of MSOAs. Just [download
existing output](outputs.qmd) if your study area matches what we provide.

## Dependencies

- **Rust**: The latest version of Rust (1.60):
  [https://www.rust-lang.org/tools/install](https://www.rust-lang.org/tools/install)

- A build environment for [proj](https://proj.org), to transform coordinates.
  - On Ubuntu, run `apt-get install cmake sqlite3 libclang-dev`
  - On Mac, [install Homebrew](https://brew.sh) and run `brew install pkg-config cmake proj`

## Compiling SPC

```shell
git clone https://github.com/alan-turing-institute/uatk-spc/
cd uatk-spc
# The next command will take a few minutes the first time you do it, to build external dependencies
cargo build --release
```

If you get `error: failed to run custom build command for 'proj-sys v0.18.4'`,
then you're likely missing dependencies listed above. Please [open an
issue](https://github.com/alan-turing-institute/uatk-spc/issues) if you have
any trouble.

## Troubleshooting downloading

If you have trouble downloading any of the large files, you can download them
manually. The logs will contain a line such as `Downloading https://ramp0storage.blob.core.windows.net/nationaldata/QUANT_RAMP_spc.tar.gz to data/raw_data/nationaldata/QUANT_RAMP_spc.tar.gz`. This tells you the URL to
retrieve, and where to put the output file. Note that SPC won't attempt to
download files if they already exist, so if you wind up with a partially
downloaded file, you have to manually remove it.
