---
title: "Modelling methods"
toc: true
---

The principles behind the generation of the enriched [SPENSER](https://osf.io/623qz/) population data and behind the modelling of trips to schools and retail from [QUANT](https://github.com/maptube/QUANT_RAMP) are detailed in

> Spooner F et al. A dynamic microsimulation model for epidemics. Soc Sci Med. 291:114461 (2021). ([DOI](https://doi.org/10.1016/j.socscimed.2021.114461))

## Commuting flows

In order to distribute each individual of the population to a unique physical workplace, we first created a population of all individual workplaces in England, based on a combination of the Nomis UK Business Counts 2020 dataset and the Nomis Business register and Employment Survey 2015 (see [Data sources](data_sources.qmd)). The first dataset gives the number of individual workplace counts per industry, using the SIC 2007 industry classification, with imprecise size (i.e. number of employees) bands at MSOA level. The second dataset gives the total number of jobs available at LSOA level per SIC 2007 industry category. We found that the distribution of workplace sizes follows closely a simple 1/x distribution, allowing us to draw for each workplace a size within their band, with sum constraints given by the total number of jobs available, according to the second dataset.

The workplace 'population' and individual population are then levelled for each SIC 2007 category by removing the exceeding part of whichever dataset lists more items. This takes into account that people and business companies are likely to over-report their working availability (e.g. part time and seasonal contracts are not counted differently than full time contracts, jobseekers or people on maternity leave might report the SIC of their last job). This process can be controlled by a threshold in the parameter file that defines the maximal total proportion of workers or jobs that can be removed. If the two datasets cannot be levelled accordingly, the categories are dropped and the datasets are levelled globally. Tests in the West Yorkshire area have shown than when the level 1 SIC, containing 21 unique categories, is used, 90% of the volume of commuting flows were recovered compared to the Nomis commuting OD matrices at MSOA level.

The employees for each workplace are drawn according to the 'universal law of visitation', see

> Schläpfer M et al. The universal visitation law of human mobility. Nature 593, 522–527 (2021). ([DOI](https://doi.org/10.1038/s41586-021-03480-9))

This framework predicts that visitors to any destination follow a simple

<p align=center> &rho;(<i>r</i>,<i>f</i>)= <i>K</i> / (<i>rf</i>)<sup>2</sup> </p align=center>
distribution, where &rho;(<i>r</i>,<i>f</i>) is the density of visitors coming from a distance <i>r</i> with frequency <i>f</i> and <i>K</i> is a balancing constant depending on the specific area. In the context of commuting, it can be assumed that <i>f</i> = 1. Additionally, we only need to weigh potential employees against each other, which removes the necessity to compute explicitly  <i>K</i>. In the West Yorkshire test, we found a Pearson coefficient of 0.7 between the predicted flows when aggregated at MSOA level and the OD matrix at MSOA level available from Nomis.

## Income data

This modelling is based on the 2020 revised edition of the [Earnings and hours worked, region by occupation by four-digit SOC: ASHE Table 15](https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/earningsandworkinghours/datasets/regionbyoccupation4digitsoc2010ashetable15) database from ONS. Some percentiles for employees' gross hourly salaries are provided for each full-time and  part-time job according to their four-digit SOC classification per region, and separated by sex.

### Methods

The data are far from complete (only about 15% of all possible values), especially for the highest deciles. We found that an order 3 polynomial fit was satisfactory for most categories (93.11%) to complete the partially filled SOCs. SOCs with too many missing values are given the value for the category that is immediately higher in the SOC hierarchy. Some jobs appear to have a 'ceiling' for the highest percentiles, making the polynomial fit fail. In that case, we have replaced the unknown values by the highest known value in the raw data (as there is no clear and systemic fit for these special cases). In addition, there is no information for the highest decile in all cases, which means that the highest salaries are underestimated (and exceptionally high salaries cannot be obtained). The result of this phase is four tables {male full-time, male part-time, female full-time, female part-time} containing the coefficients of the fitted order 3 polynomial, with an optional ceiling percentile when relevant.

A percentile is chosen randomly (uniformly) for each individual, and the salary is then deduced according to their full-time/part-time status, region, sex and SOC category. A basic hourly salary column is added to the unprocessed SPC data, as well as a corresponding annual salary based on their estimated hours worked per day, according to the Time Use Survey matching. In addition, we repeat this process for all individuals that are categorised as 'Self-employed' or 'Employee unspecified' by the Time Use Survey matching as if they were full time employees. These values are recorded in the columns `IncomeHAsIF` and `IncomeYAsIf`. We noticed that a high number of employees were given no worked hours by the Time Use Survey. We have added to the `IncomeYAsIf` column an estimation of the annual salry based on [Table 15.9a: Paid hours worked - Total 2020](Earnings and hours worked, region by occupation by four-digit SOC: ASHE Table 15) and also depending on the same four variable as above (full-time/part-time status, region, sex and SOC category).

The <i>R</i> code for this modelling is [here](https://github.com/alan-turing-institute/uatk-spc/blob/main/scripts/data_prep/incomeModelling.R).

The methods are validated in the next section. Since it is not possible to optimise every criterion at once, this next secton can also be used as a reference to re-adjust some values to match exactly the ONS estimated means for one particular criterion of interest.

### Comparison to reference values from ONS

We compare the results of the modelling to the raw datasets from ONS (M means modelled, H means hourly gross salary, Y means annual gross salary, Nat means National, FT means Full-Time, PT means Part-Time). Only individuals recorded as employees (i.e. not self-employed) are taken into account in this section.

*Number of employees (varies depending on reference dataset, reported by ONS as indicative only)*

           | Nat All | Nat FT | Nat PT | Nat Male | Nat Male FT | Nat Male PT | Nat Female | Nat Female FT | Nat Female PT |
           |---------|--------|--------|----------|-------------|-------------|------------|---------------|---------------|
number     | 22-26k  | 16-19k | 6-8k   | 11-13k   | 9-11k       | 1.5-2k      | 11-13k     | 6.5-7.5k      | 4.5-5.5k      |
M number H | 23.1k   | 18.5k  | 4.6k   | 11.8k    | 11k         | 0.8k        | 11.3k      | 7.5k          | 3.8k          |
M number Y | 17.6k   | 14.8k  | 2.8k   | 9.4k     | 8.9k        | 0.5k        | 8.2k       | 5.9k          | 2.3k          |

A significant number of individuals listed as working either full or part time have 0 effective worked hours per day according to the Time Use Survey matching. In those cases, an hourly salary is modelled depending on their SOC, region and sex, as for any other employee, but the annual salary will be displayed as 0. It is possible to estimate their likely true number of hours worked from the same ONS dataset (Table 15.9a: Paid hours worked - Total 2020), also depending on their sex, soc and region. This calculation has been added to the "As If" column.

*Hourly gross salary per sex and full-time/part-time classification*

         | Nat All | Nat FT | Nat PT | Nat Male | Nat Male FT | Nat Male PT | Nat Female | Nat Female FT | Nat Female PT |
         |---------|--------|--------|----------|-------------|-------------|------------|---------------|---------------|
mean     | 17.63   | 18.32  | 13.93  | 18.81    | 19.12       | 14.69       | 16.19      | 17.08         | 13.68         |
median   | 13.71   | 15.15  | 10.38  | 14.84    | 15.58       | 10.12       | 12.58      | 14.42         | 10.47         |
M mean   | 16.52   | 17.30  | 13.36  | 17.69    | 18.08       | 12.35       | 15.28      | 16.17         | 13.57         |
M median | 13.79   | 14.71  | 10.30  | 14.75    | 15.16       | 9.16        | 12.80      | 14.10         | 10.55         |

The median values are quite close to the ONS values, but the mean values are always lower. This is expected, see the description of the modelling above.

*Annual gross salary per sex and full-time/part-time classification*

Only values > 0 are retained for these calculations.

         | Nat All | Nat FT | Nat PT | Nat Male | Nat Male FT | Nat Male PT | Nat Female | Nat Female FT | Nat Female PT |
         |---------|--------|--------|----------|-------------|-------------|------------|---------------|---------------|
mean     | 31,646  | 38,552 | 13,819 | 38,421   | 42,072      | 14,796      | 24,871     | 33,253        | 13,512        |
median   | 25,886  | 31,487 | 11,240 | 31,393   | 33,915      | 10,883      | 20,614     | 28,002        | 4,743         |
M mean   | 34,613  | 36,974 | 22,111 | 38,082   | 39,062      | 20,153      | 30,647     | 33,826        | 22,524        |
M median | 29,249  | 31,625 | 17,947 | 32,441   | 33311       | 17,760      | 25,964     | 29,122        | 18,138        |

The average salary for part-time employees is correct when values equal to 0 are taken into account. This suggests that the total number of hours worked for part-time employees is correct, but the way they are distributed among individuals is not. It could be due to the TUS taking a snapshot of the situation during a particular week, rather than averaging their data over the year. It appears that the TUS matching also overestimates the average number of hours worked for female employees.

*Regional differences (hourly gross salary only)*

         | East  | East Midlands | London | North East | North West | South East | South West | West Midlands | Yorkshire and The Humber |
         |-------|---------------|--------|------------|------------|------------|------------|---------------|--------------------------|
mean     | 16.74 | 15.87         | 23.78  | 15.69      | 16.36      | 17.88      | 16.36      | 16.34         | 15.76                    |
median   | 13.28 | 12.65         | 18.30  | 12.40      | 12.90      | 14.33      | 12.74      | 12.92         | 12.46                    |
M mean   | 16.68 | 15.39         | 19.38  | 5.27308    | 15.43      | 17.36      | 16.01      | 15.47         | 14.56                    |
M median | 13.91 | 13.00         | 16.42  | 12.64      | 12.78      | 14.95      | 13.66      | 12.89         | 12.72720                 |

The pearson correlations for mean and median between the modelled and raw values are and 0.93 and 0.94.

*SOC (1-digit level, hourly gross salary only)*

         | 1     | 2     | 3     | 4     | 5     | 6     | 7     | 8     | 9     |
         |-------|-------|-------|-------|-------|-------|-------|-------|-------|
mean     | 26.77 | 23.38 | 18.29 | 13.42 | 13.35 | 10.87 | 10.94 | 12.23 | 10.77 |
median   | 20.96 | 21.34 | 15.66 | 11.54 | 12.04 | 10.08 | 9.52  | 10.93 | 9.22  |
M mean   | 20.94 | 22.27 | 16.39 | 12.74 | 12.82 | 10.46 | 10.67 | 12.07 | 9.89  |
M median | 17.06 | 20.78 | 14.68 | 11.58 | 11.74 | 9.85  | 9.73  | 10.96 | 9.14  |

1. Managers, directors and senior officials; 2. Professional occupations; 3. Associate professional and technical occupations; 4. Administrative and secretarial occupations; 5. Skilled trades occupations; 6. Caring, leisure and other service occupations; 7. Sales and customer service occupations; 8. Process, plant and machine operatives; 9. Elementary occupations.

The pearson correlations for mean and median between the modelled and raw values are 0.97 and 0.97.

*Age*

The reference for this table is: [Table 6.5a   Hourly pay - Gross 2020](https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/earningsandworkinghours/datasets/agegroupashetable6)

         | 16-17 | 18-21 | 22-29 | 30-39 | 40-49 | 50-59 | 60+   |
         |-------|-------|-------|-------|-------|-------|-------|
mean     | 7.21  | 9.59  | 14.09 | 18.13 | 20.04 | 19.12 | 16.32 |
median   | 6.36  | 9.00  | 12.26 | 15.08 | 15.89 | 14.39 | 12.17 |
M mean   | 12.77 | 14.96 | 16.33 | 16.93 | 16.83 | 16.66 | 16.29 |
M median | 10.93 | 12.71 | 13.88 | 14.02 | 13.96 | 13.85 | 13.65 |

The pearson correlations for mean and median between the modelled and raw values are 0.92 and 0.92.

Note that age is not part of the inputs used to compute the estimations. It can therefore be considered as an independent control of the accuracy of the method and of the SPENSER/TUS/HSE matching.
