---
title: "Outputs for England Counties"
toc: true
---

You don't need to run SPC yourself. See
[config/](https://github.com/alan-turing-institute/uatk-spc/tree/main/config)
for the list of MSOAs covered by each study area. If you want to run SPC for a
different list of MSOAs, [see here](custom_areas.qmd).

- [England/2012/bedfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/bedfordshire.pb.gz)
- [England/2012/berkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/berkshire.pb.gz)
- [England/2012/bristol.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/bristol.pb.gz)
- [England/2012/buckinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/buckinghamshire.pb.gz)
- [England/2012/cambridgeshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/cambridgeshire.pb.gz)
- [England/2012/cheshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/cheshire.pb.gz)
- [England/2012/cornwall.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/cornwall.pb.gz)
- [England/2012/cumbria.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/cumbria.pb.gz)
- [England/2012/derbyshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/derbyshire.pb.gz)
- [England/2012/devon.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/devon.pb.gz)
- [England/2012/durham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/durham.pb.gz)
- [England/2012/east-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/east-sussex.pb.gz)
- [England/2012/east-yorkshire-with-hull.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/east-yorkshire-with-hull.pb.gz)
- [England/2012/essex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/essex.pb.gz)
- [England/2012/gloucestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/gloucestershire.pb.gz)
- [England/2012/greater-london.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/greater-london.pb.gz)
- [England/2012/greater-manchester.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/greater-manchester.pb.gz)
- [England/2012/hampshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/hampshire.pb.gz)
- [England/2012/herefordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/herefordshire.pb.gz)
- [England/2012/hertfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/hertfordshire.pb.gz)
- [England/2012/isle-of-wight.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/isle-of-wight.pb.gz)
- [England/2012/kent.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/kent.pb.gz)
- [England/2012/lancashire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/lancashire.pb.gz)
- [England/2012/leicestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/leicestershire.pb.gz)
- [England/2012/lincolnshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/lincolnshire.pb.gz)
- [England/2012/merseyside.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/merseyside.pb.gz)
- [England/2012/norfolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/norfolk.pb.gz)
- [England/2012/northamptonshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/northamptonshire.pb.gz)
- [England/2012/northumberland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/northumberland.pb.gz)
- [England/2012/north-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/north-yorkshire.pb.gz)
- [England/2012/nottinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/nottinghamshire.pb.gz)
- [England/2012/oxfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/oxfordshire.pb.gz)
- [England/2012/rutland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/rutland.pb.gz)
- [England/2012/shropshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/shropshire.pb.gz)
- [England/2012/somerset.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/somerset.pb.gz)
- [England/2012/south-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/south-yorkshire.pb.gz)
- [England/2012/staffordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/staffordshire.pb.gz)
- [England/2012/suffolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/suffolk.pb.gz)
- [England/2012/surrey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/surrey.pb.gz)
- [England/2012/tyne-and-wear.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/tyne-and-wear.pb.gz)
- [England/2012/warwickshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/warwickshire.pb.gz)
- [England/2012/west-midlands.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/west-midlands.pb.gz)
- [England/2012/west-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/west-sussex.pb.gz)
- [England/2012/west-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/west-yorkshire.pb.gz)
- [England/2012/wiltshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/wiltshire.pb.gz)
- [England/2012/worcestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2012/worcestershire.pb.gz)
- [England/2020/bedfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/bedfordshire.pb.gz)
- [England/2020/berkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/berkshire.pb.gz)
- [England/2020/bristol.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/bristol.pb.gz)
- [England/2020/buckinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/buckinghamshire.pb.gz)
- [England/2020/cambridgeshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/cambridgeshire.pb.gz)
- [England/2020/cheshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/cheshire.pb.gz)
- [England/2020/cornwall.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/cornwall.pb.gz)
- [England/2020/cumbria.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/cumbria.pb.gz)
- [England/2020/derbyshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/derbyshire.pb.gz)
- [England/2020/devon.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/devon.pb.gz)
- [England/2020/durham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/durham.pb.gz)
- [England/2020/east-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/east-sussex.pb.gz)
- [England/2020/east-yorkshire-with-hull.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/east-yorkshire-with-hull.pb.gz)
- [England/2020/essex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/essex.pb.gz)
- [England/2020/gloucestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/gloucestershire.pb.gz)
- [England/2020/greater-london.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/greater-london.pb.gz)
- [England/2020/greater-manchester.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/greater-manchester.pb.gz)
- [England/2020/hampshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/hampshire.pb.gz)
- [England/2020/herefordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/herefordshire.pb.gz)
- [England/2020/hertfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/hertfordshire.pb.gz)
- [England/2020/isle-of-wight.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/isle-of-wight.pb.gz)
- [England/2020/kent.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/kent.pb.gz)
- [England/2020/lancashire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/lancashire.pb.gz)
- [England/2020/leicestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/leicestershire.pb.gz)
- [England/2020/lincolnshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/lincolnshire.pb.gz)
- [England/2020/merseyside.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/merseyside.pb.gz)
- [England/2020/norfolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/norfolk.pb.gz)
- [England/2020/northamptonshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/northamptonshire.pb.gz)
- [England/2020/northumberland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/northumberland.pb.gz)
- [England/2020/north-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/north-yorkshire.pb.gz)
- [England/2020/nottinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/nottinghamshire.pb.gz)
- [England/2020/oxfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/oxfordshire.pb.gz)
- [England/2020/rutland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/rutland.pb.gz)
- [England/2020/shropshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/shropshire.pb.gz)
- [England/2020/somerset.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/somerset.pb.gz)
- [England/2020/south-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/south-yorkshire.pb.gz)
- [England/2020/staffordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/staffordshire.pb.gz)
- [England/2020/suffolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/suffolk.pb.gz)
- [England/2020/surrey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/surrey.pb.gz)
- [England/2020/tyne-and-wear.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/tyne-and-wear.pb.gz)
- [England/2020/warwickshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/warwickshire.pb.gz)
- [England/2020/west-midlands.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/west-midlands.pb.gz)
- [England/2020/west-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/west-sussex.pb.gz)
- [England/2020/west-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/west-yorkshire.pb.gz)
- [England/2020/wiltshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/wiltshire.pb.gz)
- [England/2020/worcestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2020/worcestershire.pb.gz)
- [England/2022/bedfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/bedfordshire.pb.gz)
- [England/2022/berkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/berkshire.pb.gz)
- [England/2022/bristol.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/bristol.pb.gz)
- [England/2022/buckinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/buckinghamshire.pb.gz)
- [England/2022/cambridgeshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/cambridgeshire.pb.gz)
- [England/2022/cheshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/cheshire.pb.gz)
- [England/2022/cornwall.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/cornwall.pb.gz)
- [England/2022/cumbria.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/cumbria.pb.gz)
- [England/2022/derbyshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/derbyshire.pb.gz)
- [England/2022/devon.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/devon.pb.gz)
- [England/2022/durham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/durham.pb.gz)
- [England/2022/east-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/east-sussex.pb.gz)
- [England/2022/east-yorkshire-with-hull.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/east-yorkshire-with-hull.pb.gz)
- [England/2022/essex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/essex.pb.gz)
- [England/2022/gloucestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/gloucestershire.pb.gz)
- [England/2022/greater-london.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/greater-london.pb.gz)
- [England/2022/greater-manchester.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/greater-manchester.pb.gz)
- [England/2022/hampshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/hampshire.pb.gz)
- [England/2022/herefordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/herefordshire.pb.gz)
- [England/2022/hertfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/hertfordshire.pb.gz)
- [England/2022/isle-of-wight.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/isle-of-wight.pb.gz)
- [England/2022/kent.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/kent.pb.gz)
- [England/2022/lancashire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/lancashire.pb.gz)
- [England/2022/leicestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/leicestershire.pb.gz)
- [England/2022/lincolnshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/lincolnshire.pb.gz)
- [England/2022/merseyside.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/merseyside.pb.gz)
- [England/2022/norfolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/norfolk.pb.gz)
- [England/2022/northamptonshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/northamptonshire.pb.gz)
- [England/2022/northumberland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/northumberland.pb.gz)
- [England/2022/north-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/north-yorkshire.pb.gz)
- [England/2022/nottinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/nottinghamshire.pb.gz)
- [England/2022/oxfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/oxfordshire.pb.gz)
- [England/2022/rutland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/rutland.pb.gz)
- [England/2022/shropshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/shropshire.pb.gz)
- [England/2022/somerset.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/somerset.pb.gz)
- [England/2022/south-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/south-yorkshire.pb.gz)
- [England/2022/staffordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/staffordshire.pb.gz)
- [England/2022/suffolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/suffolk.pb.gz)
- [England/2022/surrey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/surrey.pb.gz)
- [England/2022/tyne-and-wear.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/tyne-and-wear.pb.gz)
- [England/2022/warwickshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/warwickshire.pb.gz)
- [England/2022/west-midlands.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/west-midlands.pb.gz)
- [England/2022/west-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/west-sussex.pb.gz)
- [England/2022/west-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/west-yorkshire.pb.gz)
- [England/2022/wiltshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/wiltshire.pb.gz)
- [England/2022/worcestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2022/worcestershire.pb.gz)
- [England/2032/bedfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/bedfordshire.pb.gz)
- [England/2032/berkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/berkshire.pb.gz)
- [England/2032/bristol.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/bristol.pb.gz)
- [England/2032/buckinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/buckinghamshire.pb.gz)
- [England/2032/cambridgeshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/cambridgeshire.pb.gz)
- [England/2032/cheshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/cheshire.pb.gz)
- [England/2032/cornwall.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/cornwall.pb.gz)
- [England/2032/cumbria.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/cumbria.pb.gz)
- [England/2032/derbyshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/derbyshire.pb.gz)
- [England/2032/devon.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/devon.pb.gz)
- [England/2032/durham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/durham.pb.gz)
- [England/2032/east-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/east-sussex.pb.gz)
- [England/2032/east-yorkshire-with-hull.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/east-yorkshire-with-hull.pb.gz)
- [England/2032/essex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/essex.pb.gz)
- [England/2032/gloucestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/gloucestershire.pb.gz)
- [England/2032/greater-london.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/greater-london.pb.gz)
- [England/2032/greater-manchester.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/greater-manchester.pb.gz)
- [England/2032/hampshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/hampshire.pb.gz)
- [England/2032/herefordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/herefordshire.pb.gz)
- [England/2032/hertfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/hertfordshire.pb.gz)
- [England/2032/isle-of-wight.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/isle-of-wight.pb.gz)
- [England/2032/kent.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/kent.pb.gz)
- [England/2032/lancashire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/lancashire.pb.gz)
- [England/2032/leicestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/leicestershire.pb.gz)
- [England/2032/lincolnshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/lincolnshire.pb.gz)
- [England/2032/merseyside.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/merseyside.pb.gz)
- [England/2032/norfolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/norfolk.pb.gz)
- [England/2032/northamptonshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/northamptonshire.pb.gz)
- [England/2032/northumberland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/northumberland.pb.gz)
- [England/2032/north-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/north-yorkshire.pb.gz)
- [England/2032/nottinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/nottinghamshire.pb.gz)
- [England/2032/oxfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/oxfordshire.pb.gz)
- [England/2032/rutland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/rutland.pb.gz)
- [England/2032/shropshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/shropshire.pb.gz)
- [England/2032/somerset.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/somerset.pb.gz)
- [England/2032/south-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/south-yorkshire.pb.gz)
- [England/2032/staffordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/staffordshire.pb.gz)
- [England/2032/suffolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/suffolk.pb.gz)
- [England/2032/surrey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/surrey.pb.gz)
- [England/2032/tyne-and-wear.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/tyne-and-wear.pb.gz)
- [England/2032/warwickshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/warwickshire.pb.gz)
- [England/2032/west-midlands.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/west-midlands.pb.gz)
- [England/2032/west-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/west-sussex.pb.gz)
- [England/2032/west-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/west-yorkshire.pb.gz)
- [England/2032/wiltshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/wiltshire.pb.gz)
- [England/2032/worcestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2032/worcestershire.pb.gz)
- [England/2039/bedfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/bedfordshire.pb.gz)
- [England/2039/berkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/berkshire.pb.gz)
- [England/2039/bristol.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/bristol.pb.gz)
- [England/2039/buckinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/buckinghamshire.pb.gz)
- [England/2039/cambridgeshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/cambridgeshire.pb.gz)
- [England/2039/cheshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/cheshire.pb.gz)
- [England/2039/cornwall.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/cornwall.pb.gz)
- [England/2039/cumbria.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/cumbria.pb.gz)
- [England/2039/derbyshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/derbyshire.pb.gz)
- [England/2039/devon.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/devon.pb.gz)
- [England/2039/durham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/durham.pb.gz)
- [England/2039/east-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/east-sussex.pb.gz)
- [England/2039/east-yorkshire-with-hull.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/east-yorkshire-with-hull.pb.gz)
- [England/2039/essex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/essex.pb.gz)
- [England/2039/gloucestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/gloucestershire.pb.gz)
- [England/2039/greater-london.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/greater-london.pb.gz)
- [England/2039/greater-manchester.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/greater-manchester.pb.gz)
- [England/2039/hampshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/hampshire.pb.gz)
- [England/2039/herefordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/herefordshire.pb.gz)
- [England/2039/hertfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/hertfordshire.pb.gz)
- [England/2039/isle-of-wight.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/isle-of-wight.pb.gz)
- [England/2039/kent.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/kent.pb.gz)
- [England/2039/lancashire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/lancashire.pb.gz)
- [England/2039/leicestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/leicestershire.pb.gz)
- [England/2039/lincolnshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/lincolnshire.pb.gz)
- [England/2039/merseyside.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/merseyside.pb.gz)
- [England/2039/norfolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/norfolk.pb.gz)
- [England/2039/northamptonshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/northamptonshire.pb.gz)
- [England/2039/northumberland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/northumberland.pb.gz)
- [England/2039/north-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/north-yorkshire.pb.gz)
- [England/2039/nottinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/nottinghamshire.pb.gz)
- [England/2039/oxfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/oxfordshire.pb.gz)
- [England/2039/rutland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/rutland.pb.gz)
- [England/2039/shropshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/shropshire.pb.gz)
- [England/2039/somerset.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/somerset.pb.gz)
- [England/2039/south-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/south-yorkshire.pb.gz)
- [England/2039/staffordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/staffordshire.pb.gz)
- [England/2039/suffolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/suffolk.pb.gz)
- [England/2039/surrey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/surrey.pb.gz)
- [England/2039/tyne-and-wear.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/tyne-and-wear.pb.gz)
- [England/2039/warwickshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/warwickshire.pb.gz)
- [England/2039/west-midlands.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/west-midlands.pb.gz)
- [England/2039/west-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/west-sussex.pb.gz)
- [England/2039/west-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/west-yorkshire.pb.gz)
- [England/2039/wiltshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/wiltshire.pb.gz)
- [England/2039/worcestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/England/2039/worcestershire.pb.gz)
- [special/2012/northwest_transpennine.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/special/2012/northwest_transpennine.pb.gz)
- [special/2020/northwest_transpennine.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/special/2020/northwest_transpennine.pb.gz)
- [special/2022/northwest_transpennine.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/special/2022/northwest_transpennine.pb.gz)
- [special/2032/northwest_transpennine.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/special/2032/northwest_transpennine.pb.gz)
- [special/2039/northwest_transpennine.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/special/2039/northwest_transpennine.pb.gz)
- [Wales/2012/bridgend-and-neath-port-talbot.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2012/bridgend-and-neath-port-talbot.pb.gz)
- [Wales/2012/cardiff-and-vale-of-glamorgan.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2012/cardiff-and-vale-of-glamorgan.pb.gz)
- [Wales/2012/central-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2012/central-valleys.pb.gz)
- [Wales/2012/conwy-and-denbighshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2012/conwy-and-denbighshire.pb.gz)
- [Wales/2012/flintshire-and-wrexham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2012/flintshire-and-wrexham.pb.gz)
- [Wales/2012/gwent-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2012/gwent-valleys.pb.gz)
- [Wales/2012/gwynedd.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2012/gwynedd.pb.gz)
- [Wales/2012/isle-of-anglesey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2012/isle-of-anglesey.pb.gz)
- [Wales/2012/monmouthshire-and-newport.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2012/monmouthshire-and-newport.pb.gz)
- [Wales/2012/powys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2012/powys.pb.gz)
- [Wales/2012/south-west-wales.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2012/south-west-wales.pb.gz)
- [Wales/2012/swansea.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2012/swansea.pb.gz)
- [Wales/2020/bridgend-and-neath-port-talbot.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2020/bridgend-and-neath-port-talbot.pb.gz)
- [Wales/2020/cardiff-and-vale-of-glamorgan.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2020/cardiff-and-vale-of-glamorgan.pb.gz)
- [Wales/2020/central-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2020/central-valleys.pb.gz)
- [Wales/2020/conwy-and-denbighshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2020/conwy-and-denbighshire.pb.gz)
- [Wales/2020/flintshire-and-wrexham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2020/flintshire-and-wrexham.pb.gz)
- [Wales/2020/gwent-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2020/gwent-valleys.pb.gz)
- [Wales/2020/gwynedd.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2020/gwynedd.pb.gz)
- [Wales/2020/isle-of-anglesey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2020/isle-of-anglesey.pb.gz)
- [Wales/2020/monmouthshire-and-newport.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2020/monmouthshire-and-newport.pb.gz)
- [Wales/2020/powys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2020/powys.pb.gz)
- [Wales/2020/south-west-wales.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2020/south-west-wales.pb.gz)
- [Wales/2020/swansea.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2020/swansea.pb.gz)
- [Wales/2022/bridgend-and-neath-port-talbot.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2022/bridgend-and-neath-port-talbot.pb.gz)
- [Wales/2022/cardiff-and-vale-of-glamorgan.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2022/cardiff-and-vale-of-glamorgan.pb.gz)
- [Wales/2022/central-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2022/central-valleys.pb.gz)
- [Wales/2022/conwy-and-denbighshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2022/conwy-and-denbighshire.pb.gz)
- [Wales/2022/flintshire-and-wrexham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2022/flintshire-and-wrexham.pb.gz)
- [Wales/2022/gwent-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2022/gwent-valleys.pb.gz)
- [Wales/2022/gwynedd.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2022/gwynedd.pb.gz)
- [Wales/2022/isle-of-anglesey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2022/isle-of-anglesey.pb.gz)
- [Wales/2022/monmouthshire-and-newport.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2022/monmouthshire-and-newport.pb.gz)
- [Wales/2022/powys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2022/powys.pb.gz)
- [Wales/2022/south-west-wales.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2022/south-west-wales.pb.gz)
- [Wales/2022/swansea.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2022/swansea.pb.gz)
- [Wales/2032/bridgend-and-neath-port-talbot.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2032/bridgend-and-neath-port-talbot.pb.gz)
- [Wales/2032/cardiff-and-vale-of-glamorgan.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2032/cardiff-and-vale-of-glamorgan.pb.gz)
- [Wales/2032/central-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2032/central-valleys.pb.gz)
- [Wales/2032/conwy-and-denbighshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2032/conwy-and-denbighshire.pb.gz)
- [Wales/2032/flintshire-and-wrexham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2032/flintshire-and-wrexham.pb.gz)
- [Wales/2032/gwent-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2032/gwent-valleys.pb.gz)
- [Wales/2032/gwynedd.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2032/gwynedd.pb.gz)
- [Wales/2032/isle-of-anglesey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2032/isle-of-anglesey.pb.gz)
- [Wales/2032/monmouthshire-and-newport.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2032/monmouthshire-and-newport.pb.gz)
- [Wales/2032/powys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2032/powys.pb.gz)
- [Wales/2032/south-west-wales.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2032/south-west-wales.pb.gz)
- [Wales/2032/swansea.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2032/swansea.pb.gz)
- [Wales/2039/bridgend-and-neath-port-talbot.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2039/bridgend-and-neath-port-talbot.pb.gz)
- [Wales/2039/cardiff-and-vale-of-glamorgan.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2039/cardiff-and-vale-of-glamorgan.pb.gz)
- [Wales/2039/central-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2039/central-valleys.pb.gz)
- [Wales/2039/conwy-and-denbighshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2039/conwy-and-denbighshire.pb.gz)
- [Wales/2039/flintshire-and-wrexham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2039/flintshire-and-wrexham.pb.gz)
- [Wales/2039/gwent-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2039/gwent-valleys.pb.gz)
- [Wales/2039/gwynedd.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2039/gwynedd.pb.gz)
- [Wales/2039/isle-of-anglesey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2039/isle-of-anglesey.pb.gz)
- [Wales/2039/monmouthshire-and-newport.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2039/monmouthshire-and-newport.pb.gz)
- [Wales/2039/powys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2039/powys.pb.gz)
- [Wales/2039/south-west-wales.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2039/south-west-wales.pb.gz)
- [Wales/2039/swansea.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2/Wales/2039/swansea.pb.gz)

## Citing

If you use SPC code or data in your work, please cite using the [Zenodo
DOI](https://zenodo.org/badge/latestdoi/479038905) (using the bottom-right tool
to generate the citation).

## Versioning

Over time, we may add more data to SPC or change the schema. Protocol buffers
are designed to let combinations of new/old code and data files work together,
but we don't intend to use this feature. We may make breaking changes, like
deleting fields. We'll release a new version of the schema and output data
every time and document it here. You should depend on a specific version of the
data output in your code, so new releases don't affect you until you decide to
update.

- v1: released 25/04/2022, [schema](https://github.com/alan-turing-institute/uatk-spc/blob/a9e8b361e942ba67a93f9b5b6a7d66b7ff8b0239/synthpop.proto)
- v1.1, released 27/05/2022, [schema](https://github.com/alan-turing-institute/uatk-spc/blob/570b65962d0595c0b28e0cf3554d1dd668b3932b/synthpop.proto)
  - added `pwkstat`, `salary_hourly`, `salary_yearly`, and `idp`
  - reorganized `Identifiers` and `Employment` attributes
  - non-breaking change added 02/08/2022: added `bmi_new` field
- v1.2, released 29/12/2022, [schema](https://github.com/alan-turing-institute/uatk-spc/blob/86c550e738a4f9cde052a8e33f0f9d5dcdf6000d/synthpop.proto)
  - switched to proto2 and made some fields optional
  - adjusted some numeric enum values to match ONS
- v2, released 09/03/2023, schema
  - new per-person and per-household fields
  - various changes to existing fields (adjusting enum number, removing the BMI enum, etc)
  - adding time-use diaries
  - expanding to Wales
  - adding multiple years of output
