---
title: "Performance"
toc: true
---

The following tables summarizes the resources SPC needs to run in different areas.

| study_area               | num_msoas | num_households | num_people | pb_file_size | runtime    | commuting_runtime | memory_usage |
| ------------------------ | --------- | -------------- | ---------- | ------------ | ---------- | ----------------- | ------------ |
| bedfordshire             | 74        | 271,487        | 650,950    | 94.33MiB     | 13 seconds | 6 seconds         | 293.76MiB    |
| berkshire                | 107       | 363,653        | 878,045    | 127.21MiB    | 14 seconds | 7 seconds         | 300.25MiB    |
| bristol                  | 55        | 196,230        | 456,532    | 68.11MiB     | 5 seconds  | 2 seconds         | 151.48MiB    |
| buckinghamshire          | 99        | 324,843        | 759,879    | 109.30MiB    | 10 seconds | 5 seconds         | 297.42MiB    |
| cambridgeshire           | 98        | 346,532        | 834,141    | 120.30MiB    | 13 seconds | 7 seconds         | 300.23MiB    |
| cheshire                 | 139       | 463,106        | 1,040,634  | 150.80MiB    | 15 seconds | 6 seconds         | 304.91MiB    |
| cornwall                 | 74        | 246,873        | 564,604    | 83.30MiB     | 7 seconds  | 2 seconds         | 277.31MiB    |
| cumbria                  | 64        | 224,779        | 485,035    | 70.69MiB     | 8 seconds  | 3 seconds         | 152.02MiB    |
| derbyshire               | 131       | 457,791        | 1,024,952  | 148.85MiB    | 17 seconds | 9 seconds         | 304.58MiB    |
| devon                    | 156       | 521,790        | 1,178,315  | 171.93MiB    | 20 seconds | 10 seconds        | 556.07MiB    |
| dorset                   | 95        | 344,246        | 751,334    | 109.25MiB    | 10 seconds | 5 seconds         | 298.97MiB    |
| durham                   | 117       | 406,164        | 904,785    | 130.75MiB    | 10 seconds | 4 seconds         | 299.72MiB    |
| east_sussex              | 102       | 380,180        | 830,761    | 120.14MiB    | 11 seconds | 5 seconds         | 299.81MiB    |
| east_yorkshire_with_hull | 75        | 261,267        | 579,746    | 85.31MiB     | 7 seconds  | 2 seconds         | 278.80MiB    |
| essex                    | 211       | 771,734        | 1,798,893  | 261.01MiB    | 34 seconds | 23 seconds        | 600.82MiB    |
| gloucestershire          | 107       | 392,120        | 901,395    | 129.84MiB    | 13 seconds | 5 seconds         | 302.14MiB    |
| greater_london           | 983       | 3,135,814      | 8,672,103  | 1.23GiB      | 11 minutes | 10 minutes        | 4.32GiB      |
| greater_manchester       | 346       | 871,651        | 2,746,858  | 389.21MiB    | 2 minutes  | 84 seconds        | 1.08GiB      |
| hampshire                | 225       | 775,203        | 1,803,991  | 262.78MiB    | 41 seconds | 29 seconds        | 601.86MiB    |
| herefordshire            | 23        | 83,115         | 191,282    | 27.72MiB     | 4 seconds  | 1 second          | 74.83MiB     |
| hertfordshire            | 153       | 492,783        | 1,144,974  | 165.59MiB    | 19 seconds | 11 seconds        | 555.75MiB    |
| isle_of_wight            | 18        | 64,602         | 135,125    | 20.48MiB     | 3 seconds  | 1 second          | 70.05MiB     |
| kent                     | 220       | 692,896        | 1,808,206  | 259.58MiB    | 29 seconds | 18 seconds        | 599.43MiB    |
| lancashire               | 191       | 603,524        | 1,472,550  | 210.80MiB    | 22 seconds | 12 seconds        | 592.20MiB    |
| leicestershire           | 120       | 417,621        | 1,043,283  | 147.79MiB    | 17 seconds | 11 seconds        | 302.29MiB    |
| lincolnshire             | 134       | 473,854        | 1,064,174  | 153.14MiB    | 13 seconds | 6 seconds         | 551.97MiB    |
| merseyside               | 184       | 546,791        | 1,401,012  | 200.02MiB    | 25 seconds | 17 seconds        | 590.71MiB    |
| norfolk                  | 110       | 379,188        | 891,006    | 130.04MiB    | 11 seconds | 4 seconds         | 302.39MiB    |
| north_yorkshire          | 138       | 434,489        | 1,069,514  | 154.54MiB    | 14 seconds | 6 seconds         | 552.40MiB    |
| northamptonshire         | 91        | 293,580        | 733,190    | 106.21MiB    | 10 seconds | 5 seconds         | 297.24MiB    |
| northumberland           | 40        | 113,436        | 316,618    | 45.27MiB     | 5 seconds  | 1 second          | 139.76MiB    |
| northwest_transpennine   | 829       | 2,378,868      | 6,419,933  | 928.03MiB    | 6 minutes  | 6 minutes         | 2.32GiB      |
| nottinghamshire          | 138       | 413,097        | 1,139,096  | 163.50MiB    | 19 seconds | 11 seconds        | 553.29MiB    |
| oxford_cambridge_arc     | 353       | 1,152,245      | 2,823,838  | 409.60MiB    | 2 minutes  | 78 seconds        | 1.16GiB      |
| oxfordshire              | 86        | 254,974        | 669,237    | 96.27MiB     | 9 seconds  | 4 seconds         | 279.53MiB    |
| rutland                  | 5         | 16,688         | 39,475     | 5.52MiB      | 2 seconds  | 1 second          | 18.60MiB     |
| shropshire               | 62        | 153,284        | 497,064    | 70.66MiB     | 6 seconds  | 2 seconds         | 150.19MiB    |
| somerset                 | 124       | 384,165        | 944,394    | 138.07MiB    | 14 seconds | 6 seconds         | 302.66MiB    |
| south_yorkshire          | 172       | 358,717        | 1,373,401  | 191.33MiB    | 25 seconds | 18 seconds        | 554.04MiB    |
| staffordshire            | 143       | 439,176        | 1,104,925  | 157.81MiB    | 14 seconds | 7 seconds         | 552.70MiB    |
| suffolk                  | 90        | 326,760        | 739,296    | 106.71MiB    | 9 seconds  | 4 seconds         | 296.93MiB    |
| surrey                   | 151       | 461,466        | 1,136,090  | 164.06MiB    | 20 seconds | 13 seconds        | 555.61MiB    |
| tyne_and_wear            | 145       | 414,128        | 1,111,239  | 157.15MiB    | 12 seconds | 6 seconds         | 551.14MiB    |
| warwickshire             | 108       | 319,511        | 933,391    | 132.32MiB    | 16 seconds | 10 seconds        | 300.49MiB    |
| west_midlands            | 314       | 523,264        | 2,475,918  | 348.50MiB    | 38 seconds | 25 seconds        | 1.05GiB      |
| west_sussex              | 100       | 373,326        | 838,440    | 122.18MiB    | 11 seconds | 4 seconds         | 300.54MiB    |
| west_yorkshire           | 299       | 960,426        | 2,272,063  | 331.50MiB    | 42 seconds | 28 seconds        | 1.08GiB      |
| wiltshire                | 89        | 305,679        | 686,963    | 100.69MiB    | 8 seconds  | 3 seconds         | 295.39MiB    |
| worcestershire           | 85        | 254,383        | 572,751    | 83.91MiB     | 8 seconds  | 3 seconds         | 277.79MiB    |

Notes:

- `pb_file_size` refers to the size of the uncompressed protobuf file in `data/output/`
- The total `runtime` is usually dominated by matching workers to businesses, so `commuting_runtime` gives a breakdown
- Measuring memory usage of Linux processes isn't straightforward, so `memory_usage` should just be a guide
- These measurements were all taken on one developer's laptop, and they don't represent multiple runs. This table just aims to give a general sense of how long running takes.
  - That machine has 16 cores, which matters for the parallelized commuting calculation.
- `scripts/collect_stats.py` produces the table above
