---
title: "Troubleshooting"
toc: true
---

Please [open an issue](https://github.com/alan-turing-institute/uatk-spc/issues) if you have any trouble!

## Docker 

If you're having trouble building, you can run in Docker. Assuming you have Docker setup:

```shell
git clone https://github.com/alan-turing-institute/uatk-spc/
cd spc
# Build the Docker image initially. Once we publish to Docker Hub, this step
# won't be necessary.
docker build -t spc .
# Run SPC in Docker
docker run --mount type=bind,source="$(pwd)"/data,target=/spc/data -t spc /spc/target/release/spc config/bristol.txt
```
This will make the `data` directory in your directory available to the Docker image, where it'll download the large input files and produce the final output.


## Building proj

**Symptom**: When you run `cargo build --release`, you get an error like:

```shell
 error: failed to run custom build command for 'proj-sys v0.18.4'
```

**Cause**: The Rust code depends on [proj](https://proj.org) to transform coordinates. You may need to install additional dependencies to build it.

**Suggested Solution**

On Ubuntu, run:

```shell
apt-get install cmake sqlite3 libclang-dev
```

On Mac, run:

```shell
brew install pkg-config cmake proj
```

## Downloading

If you have trouble downloading any of the large files, you can download them manually. The logs will contain a line such as `Downloading https://ramp0storage.blob.core.windows.net/nationaldata/QUANT_RAMP_spc.tar.gz to data/raw_data/nationaldata/QUANT_RAMP_spc.tar.gz`. This tells you the URL to retrieve, and where to put the output file. Note that SPC won't attempt to download files if they already exist, so if you wind up with a partially downloaded file, you have to manually remove it.
