---
title: "Outputs for England (Counties)"
toc: true
---

The counties of England are in this context the lieutenancy areas, often referred to as ceremonial counties. There are officially 48 of them, although we have chosen to include the City of London within Greater London in our release. Check the year you would like to explore and pick the corresponding file based on the region you are interested. Remember if you want to explore the data you can load the output in our [SPC explorer](https://alan-turing-institute.github.io/uatk-spc/app/).

- 2012:
  - [bedfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/bedfordshire.pb.gz)
  - [berkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/berkshire.pb.gz)
  - [bristol.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/bristol.pb.gz)
  - [buckinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/buckinghamshire.pb.gz)
  - [cambridgeshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/cambridgeshire.pb.gz)
  - [cheshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/cheshire.pb.gz)
  - [cornwall.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/cornwall.pb.gz)
  - [cumbria.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/cumbria.pb.gz)
  - [derbyshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/derbyshire.pb.gz)
  - [devon.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/devon.pb.gz)
  - [dorset.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/dorset.pb.gz)
  - [durham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/durham.pb.gz)
  - [east-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/east-sussex.pb.gz)
  - [east-yorkshire-with-hull.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/east-yorkshire-with-hull.pb.gz)
  - [essex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/essex.pb.gz)
  - [gloucestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/gloucestershire.pb.gz)
  - [greater-london.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/greater-london.pb.gz) (London)
  - [greater-manchester.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/greater-manchester.pb.gz) (Manchester)
  - [hampshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/hampshire.pb.gz) (Southampton)
  - [herefordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/herefordshire.pb.gz)
  - [hertfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/hertfordshire.pb.gz)
  - [isle-of-wight.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/isle-of-wight.pb.gz)
  - [kent.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/kent.pb.gz)
  - [lancashire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/lancashire.pb.gz)
  - [leicestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/leicestershire.pb.gz)
  - [lincolnshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/lincolnshire.pb.gz)
  - [merseyside.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/merseyside.pb.gz) (Liverpool)
  - [norfolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/norfolk.pb.gz)
  - [northamptonshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/northamptonshire.pb.gz)
  - [northumberland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/northumberland.pb.gz) (Newcastle)
  - [north-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/north-yorkshire.pb.gz)
  - [nottinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/nottinghamshire.pb.gz) (Nottingham)
  - [oxfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/oxfordshire.pb.gz)
  - [rutland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/rutland.pb.gz)
  - [shropshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/shropshire.pb.gz)
  - [somerset.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/somerset.pb.gz)
  - [south-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/south-yorkshire.pb.gz) (Sheffield)
  - [staffordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/staffordshire.pb.gz)
  - [suffolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/suffolk.pb.gz)
  - [surrey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/surrey.pb.gz)
  - [tyne-and-wear.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/tyne-and-wear.pb.gz)
  - [warwickshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/warwickshire.pb.gz)
  - [west-midlands.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/west-midlands.pb.gz) (Birmingham)
  - [west-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/west-sussex.pb.gz)
  - [west-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/west-yorkshire.pb.gz) (Leeds)
  - [wiltshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/wiltshire.pb.gz)
  - [worcestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2012/worcestershire.pb.gz)

- 2020: 
  - [bedfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/bedfordshire.pb.gz)
  - [berkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/berkshire.pb.gz)
  - [bristol.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/bristol.pb.gz)
  - [buckinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/buckinghamshire.pb.gz)
  - [cambridgeshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/cambridgeshire.pb.gz)
  - [cheshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/cheshire.pb.gz)
  - [cornwall.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/cornwall.pb.gz)
  - [cumbria.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/cumbria.pb.gz)
  - [derbyshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/derbyshire.pb.gz)
  - [dorset.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/dorset.pb.gz)
  - [devon.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/devon.pb.gz)
  - [durham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/durham.pb.gz)
  - [east-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/east-sussex.pb.gz)
  - [east-yorkshire-with-hull.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/east-yorkshire-with-hull.pb.gz)
  - [essex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/essex.pb.gz)
  - [gloucestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/gloucestershire.pb.gz)
  - [greater-london.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/greater-london.pb.gz) (London)
  - [greater-manchester.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/greater-manchester.pb.gz) (Manchester)
  - [hampshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/hampshire.pb.gz) (Southampton)
  - [herefordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/herefordshire.pb.gz)
  - [hertfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/hertfordshire.pb.gz)
  - [isle-of-wight.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/isle-of-wight.pb.gz)
  - [kent.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/kent.pb.gz)
  - [lancashire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/lancashire.pb.gz)
  - [leicestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/leicestershire.pb.gz)
  - [lincolnshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/lincolnshire.pb.gz)
  - [merseyside.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/merseyside.pb.gz) (Liverpool)
  - [norfolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/norfolk.pb.gz)
  - [northamptonshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/northamptonshire.pb.gz)
  - [northumberland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/northumberland.pb.gz) (Newcastle)
  - [north-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/north-yorkshire.pb.gz)
  - [nottinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/nottinghamshire.pb.gz) (Nottingham)
  - [oxfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/oxfordshire.pb.gz)
  - [rutland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/rutland.pb.gz)
  - [shropshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/shropshire.pb.gz)
  - [somerset.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/somerset.pb.gz)
  - [south-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/south-yorkshire.pb.gz) (Sheffield)
  - [staffordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/staffordshire.pb.gz)
  - [suffolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/suffolk.pb.gz)
  - [surrey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/surrey.pb.gz)
  - [tyne-and-wear.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/tyne-and-wear.pb.gz)
  - [warwickshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/warwickshire.pb.gz)
  - [west-midlands.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/west-midlands.pb.gz) (Birmingham)
  - [west-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/west-sussex.pb.gz)
  - [west-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/west-yorkshire.pb.gz) (Leeds)
  - [wiltshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/wiltshire.pb.gz)
  - [worcestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2020/worcestershire.pb.gz)

- 2022:

  - [bedfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/bedfordshire.pb.gz)
  - [berkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/berkshire.pb.gz)
  - [bristol.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/bristol.pb.gz)
  - [buckinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/buckinghamshire.pb.gz)
  - [cambridgeshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/cambridgeshire.pb.gz)
  - [cheshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/cheshire.pb.gz)
  - [cornwall.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/cornwall.pb.gz)
  - [cumbria.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/cumbria.pb.gz)
  - [derbyshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/derbyshire.pb.gz)
  - [dorset.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/dorset.pb.gz)
  - [devon.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/devon.pb.gz)
  - [durham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/durham.pb.gz)
  - [east-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/east-sussex.pb.gz)
  - [east-yorkshire-with-hull.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/east-yorkshire-with-hull.pb.gz)
  - [essex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/essex.pb.gz)
  - [gloucestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/gloucestershire.pb.gz)
  - [greater-london.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/greater-london.pb.gz) (London)
  - [greater-manchester.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/greater-manchester.pb.gz) (Manchester)
  - [hampshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/hampshire.pb.gz) (Southampton)
  - [herefordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/herefordshire.pb.gz)
  - [hertfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/hertfordshire.pb.gz)
  - [isle-of-wight.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/isle-of-wight.pb.gz)
  - [kent.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/kent.pb.gz)
  - [lancashire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/lancashire.pb.gz)
  - [leicestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/leicestershire.pb.gz)
  - [lincolnshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/lincolnshire.pb.gz)
  - [merseyside.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/merseyside.pb.gz) (Liverpool)
  - [norfolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/norfolk.pb.gz)
  - [northamptonshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/northamptonshire.pb.gz)
  - [northumberland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/northumberland.pb.gz) (Newcastle)
  - [north-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/north-yorkshire.pb.gz)
  - [nottinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/nottinghamshire.pb.gz) (Nottingham)
  - [oxfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/oxfordshire.pb.gz)
  - [rutland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/rutland.pb.gz)
  - [shropshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/shropshire.pb.gz)
  - [somerset.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/somerset.pb.gz)
  - [south-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/south-yorkshire.pb.gz) (Sheffield)
  - [staffordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/staffordshire.pb.gz)
  - [suffolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/suffolk.pb.gz)
  - [surrey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/surrey.pb.gz)
  - [tyne-and-wear.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/tyne-and-wear.pb.gz)
  - [warwickshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/warwickshire.pb.gz)
  - [west-midlands.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/west-midlands.pb.gz) (Birmingham)
  - [west-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/west-sussex.pb.gz)
  - [west-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/west-yorkshire.pb.gz) (Leeds)
  - [wiltshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/wiltshire.pb.gz)
  - [worcestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2022/worcestershire.pb.gz)

- 2032: 
  - [bedfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/bedfordshire.pb.gz)
  - [berkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/berkshire.pb.gz)
  - [bristol.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/bristol.pb.gz)
  - [buckinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/buckinghamshire.pb.gz)
  - [cambridgeshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/cambridgeshire.pb.gz)
  - [cheshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/cheshire.pb.gz)
  - [cornwall.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/cornwall.pb.gz)
  - [cumbria.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/cumbria.pb.gz)
  - [derbyshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/derbyshire.pb.gz)
  - [devon.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/devon.pb.gz)
  - [dorset.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/dorset.pb.gz)
  - [durham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/durham.pb.gz)
  - [east-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/east-sussex.pb.gz)
  - [east-yorkshire-with-hull.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/east-yorkshire-with-hull.pb.gz)
  - [essex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/essex.pb.gz)
  - [gloucestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/gloucestershire.pb.gz)
  - [greater-london.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/greater-london.pb.gz) (London)
  - [greater-manchester.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/greater-manchester.pb.gz) (Manchester)
  - [hampshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/hampshire.pb.gz) (Southampton)
  - [herefordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/herefordshire.pb.gz)
  - [hertfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/hertfordshire.pb.gz)
  - [isle-of-wight.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/isle-of-wight.pb.gz)
  - [kent.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/kent.pb.gz)
  - [lancashire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/lancashire.pb.gz)
  - [leicestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/leicestershire.pb.gz)
  - [lincolnshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/lincolnshire.pb.gz)
  - [merseyside.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/merseyside.pb.gz) (Liverpool)
  - [norfolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/norfolk.pb.gz)
  - [northamptonshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/northamptonshire.pb.gz)
  - [northumberland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/northumberland.pb.gz) (Newcastle)
  - [north-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/north-yorkshire.pb.gz)
  - [nottinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/nottinghamshire.pb.gz) (Nottingham)
  - [oxfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/oxfordshire.pb.gz)
  - [rutland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/rutland.pb.gz)
  - [shropshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/shropshire.pb.gz)
  - [somerset.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/somerset.pb.gz)
  - [south-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/south-yorkshire.pb.gz) (Sheffield)
  - [staffordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/staffordshire.pb.gz)
  - [suffolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/suffolk.pb.gz)
  - [surrey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/surrey.pb.gz)
  - [tyne-and-wear.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/tyne-and-wear.pb.gz)
  - [warwickshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/warwickshire.pb.gz)
  - [west-midlands.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/west-midlands.pb.gz) (Birmingham)
  - [west-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/west-sussex.pb.gz)
  - [west-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/west-yorkshire.pb.gz) (Leeds)
  - [wiltshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/wiltshire.pb.gz)
  - [worcestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2032/worcestershire.pb.gz)

- 2039: 

  - [bedfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/bedfordshire.pb.gz)
  - [berkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/berkshire.pb.gz)
  - [bristol.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/bristol.pb.gz)
  - [buckinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/buckinghamshire.pb.gz)
  - [cambridgeshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/cambridgeshire.pb.gz)
  - [cheshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/cheshire.pb.gz)
  - [cornwall.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/cornwall.pb.gz)
  - [cumbria.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/cumbria.pb.gz)
  - [derbyshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/derbyshire.pb.gz)
  - [devon.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/devon.pb.gz)
  - [dorset.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/dorset.pb.gz)
  - [durham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/durham.pb.gz)
  - [east-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/east-sussex.pb.gz)
  - [east-yorkshire-with-hull.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/east-yorkshire-with-hull.pb.gz)
  - [essex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/essex.pb.gz)
  - [gloucestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/gloucestershire.pb.gz)
  - [greater-london.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/greater-london.pb.gz) (London)
  - [greater-manchester.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/greater-manchester.pb.gz) (Manchester)
  - [hampshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/hampshire.pb.gz) (Southampton)
  - [herefordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/herefordshire.pb.gz)
  - [hertfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/hertfordshire.pb.gz)
  - [isle-of-wight.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/isle-of-wight.pb.gz)
  - [kent.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/kent.pb.gz)
  - [lancashire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/lancashire.pb.gz)
  - [leicestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/leicestershire.pb.gz)
  - [lincolnshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/lincolnshire.pb.gz)
  - [merseyside.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/merseyside.pb.gz) (Liverpool)
  - [norfolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/norfolk.pb.gz)
  - [northamptonshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/northamptonshire.pb.gz)
  - [northumberland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/northumberland.pb.gz) (Newcastle)
  - [north-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/north-yorkshire.pb.gz)
  - [nottinghamshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/nottinghamshire.pb.gz) (Nottingham)
  - [oxfordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/oxfordshire.pb.gz)
  - [rutland.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/rutland.pb.gz)
  - [shropshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/shropshire.pb.gz)
  - [somerset.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/somerset.pb.gz)
  - [south-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/south-yorkshire.pb.gz) (Sheffield)
  - [staffordshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/staffordshire.pb.gz)
  - [suffolk.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/suffolk.pb.gz)
  - [surrey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/surrey.pb.gz)
  - [tyne-and-wear.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/tyne-and-wear.pb.gz)
  - [warwickshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/warwickshire.pb.gz)
  - [west-midlands.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/west-midlands.pb.gz) (Birmingham)
  - [west-sussex.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/west-sussex.pb.gz)
  - [west-yorkshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/west-yorkshire.pb.gz) (Leeds)
  - [wiltshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/wiltshire.pb.gz)
  - [worcestershire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/England/2039/worcestershire.pb.gz)

## Citing

If you use SPC code or data in your work, please cite using the [Zenodo
DOI](https://zenodo.org/badge/latestdoi/479038905) (using the bottom-right tool
to generate the citation).
