---
title: "Outputs for Wales (ITL regions)"
toc: true
---

International Territorial Level (ITL) regions are a post-brexit renaming of the former Nomenclature of Territorial Units for Statistics (NUTS) regions. In wales, the level 3 represents a grouping of the 22 unitary districts into 12 regions. Check the year you would like to explore and pick the corresponding file based on the region you are interested. Remember if you want to explore the data you can load the output in our [SPC explorer](https://alan-turing-institute.github.io/uatk-spc/app/).

- 2012:
  - [bridgend-and-neath-port-talbot.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2012/bridgend-and-neath-port-talbot.pb.gz)
  - [cardiff-and-vale-of-glamorgan.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2012/cardiff-and-vale-of-glamorgan.pb.gz)
  - [central-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2012/central-valleys.pb.gz)
  - [conwy-and-denbighshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2012/conwy-and-denbighshire.pb.gz)
  - [flintshire-and-wrexham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2012/flintshire-and-wrexham.pb.gz)
  - [gwent-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2012/gwent-valleys.pb.gz)
  - [gwynedd.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2012/gwynedd.pb.gz)
  - [isle-of-anglesey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2012/isle-of-anglesey.pb.gz)
  - [monmouthshire-and-newport.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2012/monmouthshire-and-newport.pb.gz)
  - [powys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2012/powys.pb.gz)
  - [south-west-wales.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2012/south-west-wales.pb.gz)
  - [swansea.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2012/swansea.pb.gz)

- 2020:
  - [bridgend-and-neath-port-talbot.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2020/bridgend-and-neath-port-talbot.pb.gz)
  - [cardiff-and-vale-of-glamorgan.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2020/cardiff-and-vale-of-glamorgan.pb.gz)
  - [central-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2020/central-valleys.pb.gz)
  - [conwy-and-denbighshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2020/conwy-and-denbighshire.pb.gz)
  - [flintshire-and-wrexham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2020/flintshire-and-wrexham.pb.gz)
  - [gwent-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2020/gwent-valleys.pb.gz)
  - [gwynedd.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2020/gwynedd.pb.gz)
  - [isle-of-anglesey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2020/isle-of-anglesey.pb.gz)
  - [monmouthshire-and-newport.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2020/monmouthshire-and-newport.pb.gz)
  - [powys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2020/powys.pb.gz)
  - [south-west-wales.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2020/south-west-wales.pb.gz)
  - [swansea.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2020/swansea.pb.gz)

- 2022:
  - [bridgend-and-neath-port-talbot.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2022/bridgend-and-neath-port-talbot.pb.gz)
  - [cardiff-and-vale-of-glamorgan.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2022/cardiff-and-vale-of-glamorgan.pb.gz)
  - [central-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2022/central-valleys.pb.gz)
  - [conwy-and-denbighshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2022/conwy-and-denbighshire.pb.gz)
  - [flintshire-and-wrexham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2022/flintshire-and-wrexham.pb.gz)
  - [gwent-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2022/gwent-valleys.pb.gz)
  - [gwynedd.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2022/gwynedd.pb.gz)
  - [isle-of-anglesey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2022/isle-of-anglesey.pb.gz)
  - [monmouthshire-and-newport.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2022/monmouthshire-and-newport.pb.gz)
  - [powys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2022/powys.pb.gz)
  - [south-west-wales.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2022/south-west-wales.pb.gz)
  - [swansea.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2022/swansea.pb.gz)

- 2032:
  - [bridgend-and-neath-port-talbot.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2032/bridgend-and-neath-port-talbot.pb.gz)
  - [cardiff-and-vale-of-glamorgan.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2032/cardiff-and-vale-of-glamorgan.pb.gz)
  - [central-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2032/central-valleys.pb.gz)
  - [conwy-and-denbighshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2032/conwy-and-denbighshire.pb.gz)
  - [flintshire-and-wrexham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2032/flintshire-and-wrexham.pb.gz)
  - [gwent-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2032/gwent-valleys.pb.gz)
  - [gwynedd.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2032/gwynedd.pb.gz)
  - [isle-of-anglesey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2032/isle-of-anglesey.pb.gz)
  - [monmouthshire-and-newport.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2032/monmouthshire-and-newport.pb.gz)
  - [powys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2032/powys.pb.gz)
  - [south-west-wales.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2032/south-west-wales.pb.gz)
  - [swansea.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2032/swansea.pb.gz)

- 2039:
  - [bridgend-and-neath-port-talbot.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2039/bridgend-and-neath-port-talbot.pb.gz)
  - [cardiff-and-vale-of-glamorgan.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2039/cardiff-and-vale-of-glamorgan.pb.gz)
  - [central-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2039/central-valleys.pb.gz)
  - [conwy-and-denbighshire.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2039/conwy-and-denbighshire.pb.gz)
  - [flintshire-and-wrexham.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2039/flintshire-and-wrexham.pb.gz)
  - [gwent-valleys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2039/gwent-valleys.pb.gz)
  - [gwynedd.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2039/gwynedd.pb.gz)
  - [isle-of-anglesey.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2039/isle-of-anglesey.pb.gz)
  - [monmouthshire-and-newport.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2039/monmouthshire-and-newport.pb.gz)
  - [powys.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2039/powys.pb.gz)
  - [south-west-wales.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2039/south-west-wales.pb.gz)
  - [swansea.pb.gz](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/Wales/2039/swansea.pb.gz)

## Citing

If you use SPC code or data in your work, please cite using the [Zenodo
DOI](https://zenodo.org/badge/latestdoi/479038905) (using the bottom-right tool
to generate the citation).