---
title: "SPC Outputs"
toc: true
---

We provide outputs in protocol buffer format for all lieutenancy areas (more commonly known as ceremonial counties) of England, all ITL regions of Wales (international divisions based on the former unified European territorial division system) and all police divisions of Scotland for five reference years. These regions represent coherent territorial units whose scale is particularly well suited to the [modelling methods](understanding_modelling_methods.qmd) used by SPC. In addition, we have included two interesting areas: the Liverpool-Manchester-Leeds arc and the Cambridge to Oxford arc. See [config/](https://github.com/alan-turing-institute/uatk-spc/tree/main/config)
for the full list of MSOAs covered by each area.

The [SPC Explorer](https://alan-turing-institute.github.io/uatk-spc/app/) can be used to visualise the data, understand what attributes can be obtained form SPC and get inspired about potential applications that could stem from using these outputs.

The [SPC toolkit](using_use_output.qmd#python) can be used to work with SPC outputs in Python using [pandas](https://pandas.pydata.org/) or [polars](https://pola.rs/).

If you want to run SPC for a different list of MSOAs, [see here](using_custom_areas.qmd).

The data for 2012, 2020, 2022, 2032 & 2039 are available here:

- [England](using_england_outputs.qmd)
- [Wales](using_wales_outputs.qmd)
- [Scotland](using_scotland_outputs.qmd)
- North West Transpennine ([2012](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/special/2012/northwest_transpennine.pb.gz), [2020](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/special/2020/northwest_transpennine.pb.gz), [2022](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/special/2022/northwest_transpennine.pb.gz), [2032](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/special/2032/northwest_transpennine.pb.gz), [2039](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/special/2039/northwest_transpennine.pb.gz))
- Oxford-Cambridge arc ([2012](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/special/2012/oxford_cambridge_arc.pb.gz), [2020](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/special/2020/oxford_cambridge_arc.pb.gz), [2022](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/special/2022/oxford_cambridge_arc.pb.gz), [2032](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/special/2032/oxford_cambridge_arc.pb.gz), [2039](https://ramp0storage.blob.core.windows.net/spc-output/v2.1/special/2039/oxford_cambridge_arc.pb.gz))

## Citing

If you use SPC code or data in your work, please cite using the [Zenodo
DOI](https://zenodo.org/badge/latestdoi/479038905) (using the bottom-right tool
to generate the citation).

## Versioning

Over time, we may add more data to SPC or change the schema. Protocol buffers
are designed to let combinations of new/old code and data files work together,
but we don't intend to use this feature. We may make breaking changes, like
deleting fields. We'll release a new version of the schema and output data
every time and document it here. You should depend on a specific version of the
data output in your code, so new releases don't affect you until you decide to
update.

- v1: released 25/04/2022, [schema](https://github.com/alan-turing-institute/uatk-spc/blob/a9e8b361e942ba67a93f9b5b6a7d66b7ff8b0239/synthpop.proto)
- v1.1, released 27/05/2022, [schema](https://github.com/alan-turing-institute/uatk-spc/blob/570b65962d0595c0b28e0cf3554d1dd668b3932b/synthpop.proto)
  - added `pwkstat`, `salary_hourly`, `salary_yearly`, and `idp`
  - reorganized `Identifiers` and `Employment` attributes
  - non-breaking change added 02/08/2022: added `bmi_new` field
- v1.2, released 29/12/2022, [schema](https://github.com/alan-turing-institute/uatk-spc/blob/86c550e738a4f9cde052a8e33f0f9d5dcdf6000d/synthpop.proto)
  - switched to proto2 and made some fields optional
  - adjusted some numeric enum values to match ONS
- v2, released 09/03/2023, [schema](https://github.com/alan-turing-institute/uatk-spc/blob/f550a323afadd03bd3bfdd797b66ff2276a2a6d5/synthpop.proto)
  - new per-person and per-household fields
  - various changes to existing fields (adjusting enum number, removing the BMI enum, etc)
  - adding time-use diaries
  - expanding to Wales
  - adding multiple years of output
- v2.1, released 25/07/2023, [schema](https://github.com/alan-turing-institute/uatk-spc/blob/f550a323afadd03bd3bfdd797b66ff2276a2a6d5/synthpop.proto)
  - expanding to Scotland
  - adding special area: Oxford-Cambridge arc
  - adding previously missing LADs to their counties:
    - Greater London (E09000001)
    - Cornwall (E06000053)
    - Dorset (E06000058 & E06000059)
    - Buckinghamshire (E06000060)
    - Leicestershire (E07000135)
    - Suffolk (E07000244 & E07000245)
    - Somerset (E07000246)