---
title: "Getting started"
toc: true
---

We suggest to start by exploring one of the pre-compiled areas we have made readily available:

1. Download [sample data](using_outputs.qmd) for an area in Great Britain
2. Unpack it and open it with the [web explorer](https://alan-turing-institute.github.io/uatk-spc/app/)

Possible next steps:

3. Learn more on [how to use the data](using_use_output.qmd)
4. If you need a custom area, [build](using_installation.qmd) and then [run](using_custom_areas.qmd) SPC

## What SPC does

SPC generates spatially enriched synthetic population outputs for any area that is comprised of one or more Middle-Layer Output Areas (MSOAs) in England and Wales and/or one or more Intermediary Zones (IZ) in Scotland, including Local Authority Districts - LADs. The output file generated by SPC has a granularity
of Output Area (150 ±100 households). This file is structured to help
other researchers or urban analysts to feed dynamic models, such as ABMs, for multiple
purposes where an enriched synthetic population file is required. SPC includes
a comprehensive set of variables that include sociodemographic characteristics,
daily activities, and other extra data to help you model the complexity
of British society.

## What SPC outputs

You can see all of the per-person, household, and OA information SPC provides in the
[schema](https://github.com/alan-turing-institute/uatk-spc/blob/main/synthpop.proto) and [data sources](understanding_data_sources.qmd).
We use [protocol
buffers](https://developers.google.com/protocol-buffers/docs/overview) to
efficiently encode the data and describe its shape.
