name: Build
on: [push]
jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Building proj on Windows is a mess, so not enabled yet. https://github.com/georust/proj/pull/79
        build: [linux, macos]
        include:
          - build: linux
            os: ubuntu-18.04
          - build: macos
            os: macos-latest

    steps:
      - uses: actions/checkout@master

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.61.0

      - name: Cache build
        uses: actions/cache@v2
        with:
                path: target
                # The key could include hashFiles('Cargo.lock'), but cargo will figure out what can be reused.
                key: build-${{ matrix.os }}

      - name: Build
        run: cargo check
